package app.acindar.consumosma.creaorden;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.4.fuse-redhat-00033
 * 2024-11-12T19:03:36.849-03:00
 * Generated source version: 4.0.4.fuse-redhat-00033
 *
 */
@WebService(targetNamespace = "urn:app:acindar:ConsumoSMA:CreaOrden", name = "SI_WS_TO_RFC_ZACPMF001_Req")
@XmlSeeAlso({com.sap.document.sap.rfc.functions.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWSTORFCZACPMF001Req {

    @WebMethod(operationName = "SI_WS_TO_RFC_ZACPMF001_Req", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "Z_RFC_ZACPMF001.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public com.sap.document.sap.rfc.functions.ZRFCZACPMF001Response siWSTORFCZACPMF001Req(

        @WebParam(partName = "parameters", name = "Z_RFC_ZACPMF001", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        com.sap.document.sap.rfc.functions.ZRFCZACPMF001 parameters
    );
}
